recipes:
  IRON_GEAR_WHEEL:
    items:
      IRON: 2
    duration: 2

  STONE_FURNACE:
    items:
      STONE: 5
    duration: 2

  MINER_BURNER:
    items:
      IRON:            3
      IRON_GEAR_WHEEL: 3
      STONE_FURNACE:   1
    duration: 2
